/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "gpio.h"

int main(void)
{
  /* Loop forever */
  GPIO_Config_t *led = GPIO_Init(GPIO_A, 5, GPIO_RESET);

  for (;;)
  {
     GPIO_Write(led, GPIO_SET);
     GPIO_Delay(100000);
     GPIO_Write(led, GPIO_RESET);
     GPIO_Delay(100000);
  }
}

