/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "gpio.h"
#include "StepperMotor.h"
#include "HC_SR04.h"
#include "usart.h"

int main(void)
{
  usart2_init();
  usart2_printf("Stepper + Ultrasonic Logger Start\n");

  StepperMotor_Config_t* motor = StepperMotor_Init(GPIO_B, 0, 1, 10, 11, 5);
  HC_SR04_Config_t* sensor = HC_SR04_Init(GPIO_A, 8, 9);

  const int steps = 100;

  for (int i = 0; i < steps; i++)
  {
    StepperMotor_StepForward(motor, 1);
    GPIO_Delay(20000);

    float distance = getDistanceCm(sensor);
    usart2_printf("Step %d: %.2f cm\n", i, distance);
  }

  StepperMotor_deInit(motor);
  HC_SR04_deInit(sensor);

  while (1);
}

