/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "gpio.h"
#include "StepperMotor.h"
#include "HC_SR04.h"
#include "usart.h"
#include "tim_delay.h"

int main(void)
{
  // Initialize TIM2 for microsecond delays
  TIM2_Delay_Init();
  // Initialize USART2 for serial logging
  usart2_init();
  usart2_printf("Stepper + Ultrasonic Logger Start\n");

  // Initialize ultrasonic sensor on GPIOB pins B0 (Trigger) and B1 (Echo)
  HC_SR04_Config_t* sensor = HC_SR04_Init(GPIO_B, 0, 1);

  // Initialize stepper motor on GPIOB pins B10, B11, B12, B13 with 10ms step delay
  StepperMotor_Config_t* motor = StepperMotor_Init(GPIO_A, 8, 9, 10, 11, 10);

  const int steps = 500;  // Number of steps per scan

  for (int i = 0; i < steps; i++)
  {
    // Move stepper motor one step forward
    StepperMotor_StepForward(motor, 1);

    // Measure distance at current step
    int distance = getFilteredDistanceInt(sensor, 5);  // Take average of 5 samples
    if (distance != -1)
    {
      usart2_printf("Step %d - Distance: %d cm\n", i, distance);
    }
    else
    {
      usart2_printf("Step %d - Distance read error\n", i);
    }

    // Delay between steps
    GPIO_Delay(2000);
  }

  // Deinitialize sensor and motor
  HC_SR04_deInit(sensor);
  StepperMotor_deInit(motor);

  return 0;
}

